### ISSUE TITLE
GPS is not enabled on this device

### ISSUE THREAD

**Issue by xjin-mansfieldma** [AppGeo/GPV#111]
Hello, I was brought attention that the GPS did not work on our GPV app (version 4.2.2) for the public. I tried on an iPad and Android phone, it says "GPS is not enabled on this device". Here is a link to our GPV app. 
http://gis.mansfieldma.com/map422/Viewer.aspx?state=707673384069
Could you please help?

![mansfield gpv 422 gps not enabled](https://cloud.githubusercontent.com/assets/24320723/24262476/7c45c6a4-0fd0-11e7-8a1b-8a48315b931f.png)

**Comment by pgirard** [comment]
Thank Xia.  I'll try to look into this soon.

**Comment by xjin-mansfieldma** [comment]
Thank you, Peter.

**Comment by pgirard** [comment]
The latest versions of iOS and Android do not allow retrieval of the current location from GPS when the web page is delivered from an insecure source (HTTP instead of HTTPS).  It looks like you would have to get an SSL certificate and run the GPV with HTTPS to fix this.

http://stackoverflow.com/questions/32720308/navigator-geolocation-getcurrentposition-no-longer-working-in-safari-mobile-afte

http://stackoverflow.com/questions/40256266/navigator-geolocation-getcurrentposition-watchposition-is-not-working-in-android

**Comment by xjin-mansfieldma** [comment]
Thank you, Peter, for finding the cause and a fix.
